/**
 * Mock Data for IELTS MCQ App
 * Contains sample quiz sets, questions, and user data for development
 */

import { v4 as uuidv4 } from 'uuid';

// Sample Quiz Sets
export const mockQuizSets = [
  {
    id: uuidv4(),
    title: 'IELTS Reading Practice - Academic',
    slug: 'ielts-reading-academic-1',
    description: 'Comprehensive reading practice with passages from academic texts. Perfect for band 7+ preparation.',
    topic: 'READING',
    difficulty: 'MEDIUM',
    duration: 20,
    totalQuestions: 10,
    passScore: 60,
    thumbnail: '/images/reading.jpg',
    tags: ['academic', 'reading', 'comprehension'],
    viewCount: 1520,
    attemptCount: 892,
    avgScore: 72.5,
    avgBandScore: 6.5,
    active: true,
    featured: true,
  },
  {
    id: uuidv4(),
    title: 'Listening Comprehension Test',
    slug: 'listening-comprehension-1',
    description: 'Practice your listening skills with authentic IELTS-style audio passages.',
    topic: 'LISTENING',
    difficulty: 'HARD',
    duration: 30,
    totalQuestions: 15,
    passScore: 65,
    tags: ['listening', 'audio', 'comprehension'],
    viewCount: 980,
    attemptCount: 654,
    avgScore: 68.3,
    avgBandScore: 6.0,
    active: true,
    featured: false,
  },
  {
    id: uuidv4(),
    title: 'Vocabulary Builder - Essential Words',
    slug: 'vocabulary-essential-1',
    description: 'Master essential IELTS vocabulary with context-based questions.',
    topic: 'VOCABULARY',
    difficulty: 'EASY',
    duration: 15,
    totalQuestions: 20,
    passScore: 70,
    tags: ['vocabulary', 'words', 'beginner'],
    viewCount: 2100,
    attemptCount: 1450,
    avgScore: 78.2,
    avgBandScore: 7.0,
    active: true,
    featured: true,
  },
  {
    id: uuidv4(),
    title: 'Grammar Mastery Test',
    slug: 'grammar-mastery-1',
    description: 'Test your grammar knowledge with challenging questions.',
    topic: 'GRAMMAR',
    difficulty: 'EXPERT',
    duration: 25,
    totalQuestions: 12,
    passScore: 60,
    tags: ['grammar', 'advanced', 'syntax'],
    viewCount: 756,
    attemptCount: 423,
    avgScore: 62.1,
    avgBandScore: 5.5,
    active: true,
    featured: false,
  },
];

// Sample Questions
export const mockQuestions = [
  {
    id: uuidv4(),
    order: 1,
    text: 'The author\'s main purpose in writing this passage is to:',
    type: 'SINGLE_CHOICE',
    timeLimit: 60,
    difficulty: 'MEDIUM',
    explanation: 'The passage primarily discusses the impact of climate change on marine ecosystems, making option B the correct answer.',
    options: [
      { id: 'a', text: 'Describe the history of marine biology', isCorrect: false },
      { id: 'b', text: 'Explain the effects of climate change on ocean life', isCorrect: true },
      { id: 'c', text: 'Argue against environmental regulations', isCorrect: false },
      { id: 'd', text: 'Compare different scientific methodologies', isCorrect: false },
    ],
  },
  {
    id: uuidv4(),
    order: 2,
    text: 'According to the passage, which of the following is TRUE about coral reefs?',
    type: 'SINGLE_CHOICE',
    timeLimit: 60,
    difficulty: 'MEDIUM',
    explanation: 'The passage explicitly states that coral reefs support approximately 25% of all marine species.',
    options: [
      { id: 'a', text: 'They are found only in tropical waters', isCorrect: false },
      { id: 'b', text: 'They support about 25% of all marine species', isCorrect: true },
      { id: 'c', text: 'They are not affected by temperature changes', isCorrect: false },
      { id: 'd', text: 'They have been expanding in recent years', isCorrect: false },
    ],
  },
  {
    id: uuidv4(),
    order: 3,
    text: 'The word "unprecedented" in paragraph 2 is closest in meaning to:',
    type: 'SINGLE_CHOICE',
    timeLimit: 45,
    difficulty: 'EASY',
    explanation: '"Unprecedented" means never done or known before, which is synonymous with "never before seen."',
    options: [
      { id: 'a', text: 'Expected', isCorrect: false },
      { id: 'b', text: 'Never before seen', isCorrect: true },
      { id: 'c', text: 'Gradual', isCorrect: false },
      { id: 'd', text: 'Reversible', isCorrect: false },
    ],
  },
  {
    id: uuidv4(),
    order: 4,
    text: 'Rising ocean temperatures have led to increased coral bleaching events.',
    type: 'TRUE_FALSE',
    timeLimit: 30,
    difficulty: 'EASY',
    explanation: 'This is explicitly stated in the passage as one of the main effects of climate change on coral reefs.',
    options: [
      { id: 'true', text: 'True', isCorrect: true },
      { id: 'false', text: 'False', isCorrect: false },
      { id: 'ng', text: 'Not Given', isCorrect: false },
    ],
  },
  {
    id: uuidv4(),
    order: 5,
    text: 'What does the author suggest as a potential solution to protect marine ecosystems?',
    type: 'SINGLE_CHOICE',
    timeLimit: 60,
    difficulty: 'HARD',
    explanation: 'The author emphasizes the importance of establishing marine protected areas as a key conservation strategy.',
    options: [
      { id: 'a', text: 'Increasing fishing quotas', isCorrect: false },
      { id: 'b', text: 'Building artificial reefs', isCorrect: false },
      { id: 'c', text: 'Establishing marine protected areas', isCorrect: true },
      { id: 'd', text: 'Relocating marine species', isCorrect: false },
    ],
  },
  {
    id: uuidv4(),
    order: 6,
    text: 'Choose the correct word to complete the sentence: "The research team _____ conducting experiments for three years."',
    type: 'SINGLE_CHOICE',
    timeLimit: 45,
    difficulty: 'MEDIUM',
    explanation: 'Present perfect continuous is used for actions that started in the past and continue to the present.',
    options: [
      { id: 'a', text: 'is', isCorrect: false },
      { id: 'b', text: 'has been', isCorrect: true },
      { id: 'c', text: 'have been', isCorrect: false },
      { id: 'd', text: 'was', isCorrect: false },
    ],
  },
  {
    id: uuidv4(),
    order: 7,
    text: 'The term "biodiversity" refers to:',
    type: 'SINGLE_CHOICE',
    timeLimit: 45,
    difficulty: 'EASY',
    explanation: 'Biodiversity encompasses the variety of all living organisms across all ecosystems.',
    options: [
      { id: 'a', text: 'The study of living organisms', isCorrect: false },
      { id: 'b', text: 'The variety of life in a particular habitat', isCorrect: true },
      { id: 'c', text: 'The classification of species', isCorrect: false },
      { id: 'd', text: 'The evolution of organisms', isCorrect: false },
    ],
  },
  {
    id: uuidv4(),
    order: 8,
    text: 'Which paragraph discusses the economic impact of marine ecosystem degradation?',
    type: 'SINGLE_CHOICE',
    timeLimit: 60,
    difficulty: 'HARD',
    explanation: 'Paragraph 4 specifically addresses how the decline of marine ecosystems affects coastal economies and fishing industries.',
    options: [
      { id: 'a', text: 'Paragraph 2', isCorrect: false },
      { id: 'b', text: 'Paragraph 3', isCorrect: false },
      { id: 'c', text: 'Paragraph 4', isCorrect: true },
      { id: 'd', text: 'Paragraph 5', isCorrect: false },
    ],
  },
  {
    id: uuidv4(),
    order: 9,
    text: 'The author\'s tone in this passage can best be described as:',
    type: 'SINGLE_CHOICE',
    timeLimit: 45,
    difficulty: 'MEDIUM',
    explanation: 'While presenting concerning facts, the author maintains an objective, informative tone throughout.',
    options: [
      { id: 'a', text: 'Optimistic and cheerful', isCorrect: false },
      { id: 'b', text: 'Concerned but informative', isCorrect: true },
      { id: 'c', text: 'Angry and accusatory', isCorrect: false },
      { id: 'd', text: 'Indifferent and detached', isCorrect: false },
    ],
  },
  {
    id: uuidv4(),
    order: 10,
    text: 'Based on the passage, ocean acidification is caused primarily by:',
    type: 'SINGLE_CHOICE',
    timeLimit: 60,
    difficulty: 'MEDIUM',
    explanation: 'The passage clearly states that increased CO2 absorption by oceans leads to acidification.',
    options: [
      { id: 'a', text: 'Plastic pollution', isCorrect: false },
      { id: 'b', text: 'Overfishing', isCorrect: false },
      { id: 'c', text: 'Increased CO2 absorption', isCorrect: true },
      { id: 'd', text: 'Oil spills', isCorrect: false },
    ],
  },
];

// Sample Badges
export const mockBadges = [
  { id: uuidv4(), name: 'First Steps', description: 'Complete your first quiz', icon: '🌟', rarity: 'COMMON', xpReward: 50 },
  { id: uuidv4(), name: 'Quick Learner', description: 'Answer 10 questions correctly in a row', icon: '⚡', rarity: 'RARE', xpReward: 100 },
  { id: uuidv4(), name: 'Perfectionist', description: 'Score 100% on any quiz', icon: '🏆', rarity: 'EPIC', xpReward: 200 },
  { id: uuidv4(), name: 'Dedicated', description: 'Maintain a 7-day streak', icon: '🔥', rarity: 'RARE', xpReward: 150 },
  { id: uuidv4(), name: 'Scholar', description: 'Complete 50 quizzes', icon: '🎓', rarity: 'EPIC', xpReward: 300 },
  { id: uuidv4(), name: 'Legend', description: 'Reach level 20', icon: '👑', rarity: 'LEGENDARY', xpReward: 500 },
];

// Sample Achievements
export const mockAchievements = [
  { id: uuidv4(), name: 'Practice Makes Perfect', description: 'Complete 100 questions', icon: '📚', category: 'PRACTICE', targetValue: 100, xpReward: 200 },
  { id: uuidv4(), name: 'Consistency King', description: 'Maintain a 30-day streak', icon: '👑', category: 'STREAK', targetValue: 30, xpReward: 500 },
  { id: uuidv4(), name: 'High Achiever', description: 'Achieve band 8 or higher', icon: '⭐', category: 'SCORE', targetValue: 8, xpReward: 300 },
];

// Sample Leaderboard
export const mockLeaderboard = [
  { rank: 1, name: 'Sarah Chen', xp: 15200, level: 18, avatar: 'https://ui-avatars.com/api/?name=Sarah+Chen&background=6366f1&color=fff' },
  { rank: 2, name: 'Michael Brown', xp: 14800, level: 17, avatar: 'https://ui-avatars.com/api/?name=Michael+Brown&background=ec4899&color=fff' },
  { rank: 3, name: 'Emily Wilson', xp: 13500, level: 16, avatar: 'https://ui-avatars.com/api/?name=Emily+Wilson&background=10b981&color=fff' },
  { rank: 4, name: 'James Taylor', xp: 12200, level: 15, avatar: 'https://ui-avatars.com/api/?name=James+Taylor&background=f59e0b&color=fff' },
  { rank: 5, name: 'Emma Davis', xp: 11800, level: 14, avatar: 'https://ui-avatars.com/api/?name=Emma+Davis&background=3b82f6&color=fff' },
  { rank: 6, name: 'Daniel Lee', xp: 10500, level: 13, avatar: 'https://ui-avatars.com/api/?name=Daniel+Lee&background=8b5cf6&color=fff' },
  { rank: 7, name: 'Olivia Martin', xp: 9800, level: 12, avatar: 'https://ui-avatars.com/api/?name=Olivia+Martin&background=ef4444&color=fff' },
  { rank: 8, name: 'William Garcia', xp: 9200, level: 11, avatar: 'https://ui-avatars.com/api/?name=William+Garcia&background=14b8a6&color=fff' },
  { rank: 9, name: 'Sophia Anderson', xp: 8700, level: 11, avatar: 'https://ui-avatars.com/api/?name=Sophia+Anderson&background=f97316&color=fff' },
  { rank: 10, name: 'Benjamin Thomas', xp: 8100, level: 10, avatar: 'https://ui-avatars.com/api/?name=Benjamin+Thomas&background=06b6d4&color=fff' },
];

export default {
  quizSets: mockQuizSets,
  questions: mockQuestions,
  badges: mockBadges,
  achievements: mockAchievements,
  leaderboard: mockLeaderboard,
};
